version: '3.6'
services:
  radcab:
    build: 
      context: .
    privileged: true
    restart: unless-stopped
    volumes:
      - ./config.yml:/config.yml
      - /etc/revpi/config.rsc:/config.rsc
    network_mode: host
    environment:
      - PYTHONDEBUG=DEBUG
